[project]
name = "triz-quiz"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=2.25,<3",
    "aiohttp>=3.8",
    "flask>=2.3",
    "flask-socketio>=5.3",
    "python-dotenv>=1.0",
]
