[project]
name = "triz-quiz"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "aiohttp>=3.12.15",
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "python-dotenv>=1.0.1",
]
